const products = [
  {
    _id: "1",
    name: "Almonds",
    image: "/images/almond.jpg",
    description: "Fresh roasted almonds",
    category: "plain",
    price: 150,
    countInStock: 5,
    rating: 4.6,
    numReviews: 15,
  },
  {
    _id: "2",
    name: "Rasins",
    image: "/images/raisins.jpg",
    description: "Fresh spiced raisins",
    category: "spice",
    price: 200,
    countInStock: 10,
    rating: 4.3,
    numReviews: 28,
  },
  {
    _id: "3",
    name: "Walnuts",
    image: "/images/walnut.jpg",
    description: "Fresh roasted almonds",
    category: "plain",
    price: 150,
    countInStock: 5,
    rating: 4.2,
    numReviews: 15,
  },
  {
    _id: "4",
    name: "pista",
    image: "/images/pista.jpg",
    description: "Fresh pista",
    category: "flavoured",
    price: 150,
    countInStock: 5,
    rating: 3.6,
    numReviews: 15,
  },
  {
    _id: "5",
    name: "Rasins",
    image: "/images/raisingold.jpg",
    description: "Fresh raisins",
    category: "plain",
    price: 150,
    countInStock: 0,
    rating: 2.6,
    numReviews: 15,
  },
  {
    _id: "6",
    name: "Blueberries",
    image: "/images/blueberry.jpg",
    description: "Fresh blueberries",
    category: "plain",
    price: 150,
    countInStock: 5,
    rating: 3,
    numReviews: 15,
  },
];

export default products;
